### ISSUE TITLE
Problem downloading word2vec model

### ISSUE THREAD

**Issue by entn-at** [social-machines/RadioTalk#1]
Hi,

I'm having difficulties downloading the word2vec model files. I was able to download `radiotalk.json.gz` as well as the monthly files, so there shouldn't be an issue with my AWS credentials, but the files under `s3://radio-talk/v1.0/word2vec/` result in `fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden`. Perhaps an issue with regions? I'm using awscli version 1.16.231.

Thanks,
Ewald

**Comment by wwbrannon** [comment]
Fixed! (At least it should be - let me know if you still can't download.) Thanks for flagging. It was a permissions issue.
